### ISSUE TITLE
欢杀甘夫人bug

### ISSUE THREAD

**Issue by HariShelfan** [mengxinzxz/HuoDong-update#2]
队友受伤，欢杀甘夫人会发动淑慎，但自己受伤就不会发动。

**Comment by mengxinzxz** [comment]
√

**Comment by HariShelfan** [comment]
现在欢杀甘夫人依然有这个问题，AI控制欢杀甘夫人时，自己受到1点伤害时不会发动淑慎，而自己受到两点及以上伤害或者队友受到伤害都会发动
