### ISSUE TITLE
求助，characterSubstitute中怎么匹配换武将的死亡语音呢

### ISSUE THREAD

**Issue by wxsthuee** [mengxinzxz/HuoDong-update#27]

**Comment by mengxinzxz** [comment]
以你更换的武将皮肤id为准，如果想让他匹配到本体audio/die文件夹外的配音，请在characterSubstitute[皮肤id]中同正常武将一样写阵亡配音路径

**Comment by wxsthuee** [comment]
> 以你更换的武将皮肤id为准，如果想让他匹配到本体audio/die文件夹外的配音，请在characterSubstitute[皮肤id]中同正常武将一样写阵亡配音路径

感谢回复！但是我没懂😂我按这样写，好像是不行的：

characterSubstitute: {
  ZIWU_WEI_caoying: [
    ["ZIWU_WEI_caoying_shadow", ["ext:子午奇谋/image/character/ZIWU_WEI_caoying_shadow.jpg"], ["ext:子午奇谋/audio/die/ZIWU_WEI_caoying_shadow.mp3"]],
  ],
}
