### ISSUE TITLE
无法使用欢乐三国杀武将

### ISSUE THREAD

**Issue by TianyaSKY** [mengxinzxz/HuoDong-update#3]
<img width="1280" alt="屏幕截图 2023-12-31 181631" src="https://github.com/mengxinzxz/HuoDong-update/assets/93835113/baff63a8-d393-4421-9c8f-a75468584cbf">

**Comment by mengxinzxz** [comment]
扩展写法更新已不兼容无名杀十周年版本，请更换版本或放弃使用本扩展
