### ISSUE TITLE
编辑欢杀将池显示错误

### ISSUE THREAD

**Issue by qdwxyz** [mengxinzxz/HuoDong-update#34]
编辑欢杀将池显示错误
![Screenshot_20240819_145103_com noname shijian](https://github.com/user-attachments/assets/5467221d-99ed-4cfa-aa16-98f01fa585f8)
![Screenshot_20240819_151351_com noname shijian](https://github.com/user-attachments/assets/44cba4b5-abad-4dbb-b32f-d19842900cc4)
![Screenshot_20240819_151358_com noname shijian](https://github.com/user-attachments/assets/af968544-8619-4078-97e5-75cee3de48c1)

**Comment by mengxinzxz** [comment]
已修
