### ISSUE TITLE
希望给左慈的新生彩蛋加个开关

### ISSUE THREAD

**Issue by qdwxyz** [mengxinzxz/HuoDong-update#38]
欢乐杀左慈发起新生拿完牌后会随机变成一个虚拟偶像并获得对应希望给这个彩蛋和十常侍加个开关

![Screenshot_20240831_213900_com noname shijian](https://github.com/user-attachments/assets/a4b53e46-8934-421c-a475-8db161244628)

![Screenshot_20240831_213904_com noname shijian](https://github.com/user-attachments/assets/e6666541-c562-449a-9036-144413cf117c)

**Comment by qdwxyz** [comment]
上一个图片没发好所以关闭了

**Comment by mengxinzxz** [comment]
这个是刻意的，不改了
