### ISSUE TITLE
旧版荀采的old_lieshi有bug

### ISSUE THREAD

**Issue by wxsthuee** [mengxinzxz/HuoDong-update#4]
理应只能转化成场上没有的延时锦囊牌，但是实测下来，只要场上没有真的【乐不思蜀】，荀采就可以无限转化【乐不思蜀】。
其他延时锦囊牌也是一样。
是不是转化后的延时锦囊牌，在游戏中的牌名依然是转化前的牌名？比如，用【杀】转化了【乐不思蜀】，这张牌的牌名依然是【杀】。

**Comment by mengxinzxz** [comment]
已重构技能写法
